# Server
server.port=8843

# Application
spring.application.name=ms-wf

# Oracle Datasource
spring.datasource.url=jdbc:oracle:thin:@//37.187.250.163:1521/AVA_POC
spring.datasource.username=MSWF
spring.datasource.password=MSWF

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.default_schema=MSWF
spring.jpa.open-in-view=false

# Flowable
flowable.async-executor-activate=false
flowable.database-schema-update=true
flowable.check-process-definitions=true

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration
app.jwt.secret=mySecretKeyForJwtTokenGenerationMustBeLongEnough123456789
app.jwt.expiration-ms=86400000

spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

# Hibernate Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE

