package com.example.avagen.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;

@Getter
@Setter
@Entity
@Table(name = "DECLARATION_FISCALE")
public class DeclarationFiscale {

    // Primary key: referenceDeclaration generated by DB sequence SEQ_DECLA
    @Id
    @SequenceGenerator(name = "seq_decla_gen", sequenceName = "SEQ_DECLA", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_decla_gen")
    @Column(name = "REFENRECE_DECLARATION")
    private Long referenceDeclaration;

    @Column(name = "TYPE_PIECE_CLIENT")
    private Integer typePieceClient;

    @Size(max = 13)
    @Column(name = "NO_PIECE_CLIENT", length = 13)
    private String noPieceClient;

    @Column(name = "ANNEE")
    private Short annee;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @Column(name = "DATE_DECLARATION")
    private LocalDate dateDeclaration;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @Column(name = "DATE_PRESENTATION")
    private LocalDate datePresentation;

    @Column(name = "MNT_CA_FISCAL", precision = 23, scale = 3)
    private BigDecimal mntCaFiscal;

    @Size(max = 10)
    @Column(name = "ETAT", length = 10)
    private String etat;

}