services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: mswf
      APP_USER_PASSWORD: mswf
    ports:
      - "1521:1521"
    volumes:
      - oradata:/opt/oracle/oradata

volumes:
  oradata:
